services:

  appDb:
    image: mysql
    restart: always
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
    # image: bitnami/mysql
    # restart: always
    # environment:
    #   MYSQL_ROOT_PASSWORD: toor
    #   MYSQL_DATABASE: eplanner
    # ports: 
    #   - 3306:3306
    # volumes:
    #   - ./database/migration/sql:/docker-entrypoint-initdb.d/database/migration/sql

    # healthcheck:
    #   test: ["CMD", "mysql", "-u", "root",  "-ptoor", "-e", "show schemas"]
    #   interval: 10s 

  app:
    build: .
    restart: always
    environment:
      HTTP_PORT: 8080
      STORAGE: db
    ports:
      - 8080:8080
