services:

  appDb:
    image: bitnami/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: event-planner
    ports: 
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysql", "-u", "root",  "-ptoor", "-e", "show schemas"]
      interval: 10s 

  app:
    build: .
    restart: always
    environment:
      HTTP_PORT: 8080
      CONNECTION_STRING: root:toor@tcp(172.17.0.1:3306)/event-planner?charset=utf8&parseTime=True&loc=Local
      STORAGE: db
    ports:
      - 8080:8080